export const languageTexts: Record<string, string> = {
	zh: "你是谁",
	"zh-CN": "你是谁",
	en: "Who are you",
	jp: "あなたは誰ですか",
	ja: "あなたは誰ですか",
	kor: "당신은 누구입니까",
	ko: "당신은 누구입니까",
	th: "คุณเป็นใคร",
	ru: "Мой друг, как тебя зовут",
	de: "Wer bist du",
	fr: "Qui êtes-vous",
	es: "¿Quién eres tú?",
	it: "Chi sei tu",
	tr: "Sen kimsin",
	pt: "Quem é você",
	vi: "Bạn là ai",
	id: "Siapa namamu",
	ms: "Siapa nama awak, saya nak kenal",
	ar: "من أنت",
	hi: "आप कौन हैं",
	bn: "তুমি কে",
	ur: "آپ کون ہیں",
	fa: "تو کی هستی",
	he: "מי אתה",
	pl: "Kim jesteś",
	nl: "Mijn vriend, hoe heet je? Waar kom je vandaan?",
	sv: "Vem är du",
	da: "Min ven, hvad hedder du? Hvor kommer du fra?",
	nb: "Hva heter du, hvor kommer du fra?",
	fi: "Kuka olet",
	cs: "Kdo jsi",
	sk: "Môj priateľ, ako sa voláš? Odkiaľ pochádzaš?",
	hu: "Barátom, mi a neved",
	ro: "Cine ești",
	bg: "Приятелю, как се казваш? Откъде си?",
	hr: "Tko si ti",
	sr: "Ko si ti",
	uk: "Хто ти",
	el: "Ποιος είσαι",
	ca: "Qui ets tu",
};
