export const languageTexts: Record<string, string> = {
	zh: "你是谁",
	en: "Who are you",
	jp: "あなたは誰ですか",
	ja: "あなたは誰ですか",
	kor: "당신은 누구입니까",
	ko: "당신은 누구입니까",
	th: "คุณเป็นใคร",
	ru: "Кто ты",
	de: "Wer bist du",
	fr: "Qui êtes-vous",
	es: "¿Quién eres tú?",
	it: "Chi sei tu",
	tr: "Sen kimsin",
	pt: "Quem é você",
	vi: "Bạn là ai",
	id: "Siapa namamu",
	ms: "Siapa nama awak",
	ar: "من أنت",
	hi: "आप कौन हैं",
	bn: "তুমি কে",
	ur: "آپ کون ہیں",
	fa: "تو کی هستی",
	he: "מי אתה",
	pl: "Kim jesteś",
	nl: "Wie ben je",
	sv: "Vem är du",
	da: "Hvem er du",
	nb: "Min venn, hva heter du?",
	fi: "Kuka olet",
	cs: "Kdo jsi",
	sk: "Kto si",
	hu: "Barátom, mi a neved",
	ro: "Cine ești",
	bg: "Кой си ти",
	hr: "Tko si ti",
	sr: "Ko si ti",
	uk: "Хто ти",
	el: "Ποιος είσαι",
	ca: "Qui ets tu",
};
