name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  HUSKY: 0
  AZURE_KEY: ${{ secrets.AZURE_KEY }}
  AZURE_REGION: ${{ secrets.AZURE_REGION }}
  AMAZON_REGION: ${{ secrets.AMAZON_REGION }}
  AMAZON_ACCESS_KEY_ID: ${{ secrets.AMAZON_ACCESS_KEY_ID }}
  AMAZON_SECRET_ACCESS_KEY: ${{ secrets.AMAZON_SECRET_ACCESS_KEY }}
  BAIDU_APP_ID: ${{ secrets.BAIDU_APP_ID }}
  BAIDU_SECRET_KEY: ${{ secrets.BAIDU_SECRET_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Install tsx
        run: pnpm install -g tsx

      - name: Build
        run: pnpm run build

      - name: Cache dist
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # v4.3.6
        with:
          retention-days: 3
          name: dist
          path: dist

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Install tsx
        run: pnpm install -g tsx

      - name: Restore dist cache
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: dist
          path: dist

      - name: Run tests
        run: pnpm run test

  test-coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - name: Set node version to 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Install tsx
        run: pnpm install -g tsx

      - name: Restore dist cache
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: dist
          path: dist

      - name: Run tests with coverage
        run: pnpm run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: packages/*/coverage/*.json
          flags: ${{ github.event.repository.name }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
